PD2-2127: added missing user action output
mindojo/live-visitors-interview pull request #3
Opened 2020-08-23 21:08 UTC by alexp374

https://mindojo.atlassian.net/browse/PD2-2127

2020-08-24 05:42 UTC, mindojo-victor requested changes

2020-08-24 05:42 UTC, mindojo-victor commented on lvi/actions.py
> +    if user.status is not UserStatus.ACTIVE:
`is not ` should not be used when comparing strings.

2020-08-24 05:42 UTC, mindojo-victor commented on lvi/actions.py
> +    if user.status is not UserStatus.INACTIVE:
Please find other uses of `is not` in the code and change them to `!=`

2020-08-24 10:34 UTC, alexp374 commented on lvi/actions.py
> +    if user.status is not UserStatus.ACTIVE:
it isn't a string. 
```
type(UserStatus.ACTIVE)
<enum 'UserStatus'>
```
string is `UserStatus.ACTIVE.value`

2020-08-24 10:34 UTC, alexp374 commented on lvi/actions.py
> +    if user.status is not UserStatus.INACTIVE:
same, it isn't a string

2020-08-24 10:36 UTC, mindojo-victor commented on lvi/actions.py
> +    if user.status is not UserStatus.ACTIVE:
It doesn't really matter. `is` is used for comparing ids

2020-08-24 10:38 UTC, mindojo-victor commented on lvi/actions.py
> +    if user.status is not UserStatus.ACTIVE:
Ah, I see https://docs.python.org/3/library/enum.html#comparisons
But still, I think it's a bad idea to use `is`

2020-08-24 12:03 UTC, mindojo-victor approved these changes

2020-08-24 12:07 UTC, merged

2020-08-27 06:03 UTC, andrey-dresvyannikov commented on lvi/actions.py
> +    if user.status is not UserStatus.ACTIVE:
I'm personally ok with using `is` & `is not` with `Enum`s :)

2020-08-27 06:26 UTC, mindojo-victor commented on lvi/actions.py
> +    if user.status is not UserStatus.ACTIVE:
I am not strongly against using `is`. But I think it's less cognitive load to use `==`. 
Because we almost never use `is` and it could be a sign of an error:
```
app@dev2:~/blp.dev.mndj.link/brain2$ ./manage.sh shell
/home/app/blp.dev.mndj.link/brain2/venv/lib/python3.8/site-packages/jmespath/visitor.py:32: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if x is 0 or x is 1:
/home/app/blp.dev.mndj.link/brain2/venv/lib/python3.8/site-packages/jmespath/visitor.py:32: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if x is 0 or x is 1:
/home/app/blp.dev.mndj.link/brain2/venv/lib/python3.8/site-packages/jmespath/visitor.py:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif y is 0 or y is 1:
/home/app/blp.dev.mndj.link/brain2/venv/lib/python3.8/site-packages/jmespath/visitor.py:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif y is 0 or y is 1:
/home/app/blp.dev.mndj.link/brain2/venv/lib/python3.8/site-packages/jmespath/visitor.py:260: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if original_result is 0:
/home/app/blp.dev.mndj.link/brain2/venv/lib/python3.8/site-packages/braintree/payment_method_gateway.py:121: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif result_key is "revoke" and response.get("success", False):
/home/app/blp.dev.mndj.link/brain2/venv/lib/python3.8/site-packages/braintree/payment_method_gateway.py:123: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif result_key is "payment_method_nonce":
/home/app/blp.dev.mndj.link/brain2/venv/lib/python3.8/site-packages/traitlets/config/loader.py:795: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
/home/app/blp.dev.mndj.link/brain2/venv/lib/python3.8/site-packages/traitlets/config/loader.py:804: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
```
It's like using mutable default arguments in functions knowing that you don't mutate them inside, but it's safer to not use them.